services:
  - type: web
    name: lbu-image-auth-checker
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app --chdir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
